-- MySQL Script generated by MySQL Workbench
-- Tue Mar 29 14:28:58 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ER
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ER
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ER` DEFAULT CHARACTER SET utf8 ;
USE `ER` ;

-- -----------------------------------------------------
-- Table `ER`.`Asiakas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ER`.`Asiakas` (
  `idAsiakas` INT NOT NULL AUTO_INCREMENT,
  `Etunimi` VARCHAR(45) NOT NULL,
  `Sukunimi` VARCHAR(45) NOT NULL,
  `Osoite` VARCHAR(45) NULL,
  `Puhelinnumero` BIGINT(12) NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`idAsiakas`),
  UNIQUE INDEX `idAsiakas_UNIQUE` (`idAsiakas` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ER`.`Tili`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ER`.`Tili` (
  `idTili` INT NOT NULL,
  `Tilinumero` INT NOT NULL,
  `Saldo` INT NOT NULL,
  PRIMARY KEY (`idTili`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ER`.`Kortti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ER`.`Kortti` (
  `idKortti` INT NOT NULL AUTO_INCREMENT,
  `Kortinnumero` INT NOT NULL,
  `PIN` VARCHAR(255) NOT NULL,
  `Asiakas_idAsiakas` INT NOT NULL,
  `Tili_idTili` INT NOT NULL,
  PRIMARY KEY (`idKortti`, `Asiakas_idAsiakas`, `Tili_idTili`),
  UNIQUE INDEX `Kortinnumero_UNIQUE` (`Kortinnumero` ASC) VISIBLE,
  INDEX `fk_Kortti_Asiakas_idx` (`Asiakas_idAsiakas` ASC) VISIBLE,
  INDEX `fk_Kortti_Tili1_idx` (`Tili_idTili` ASC) VISIBLE,
  CONSTRAINT `fk_Kortti_Asiakas`
    FOREIGN KEY (`Asiakas_idAsiakas`)
    REFERENCES `ER`.`Asiakas` (`idAsiakas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Kortti_Tili1`
    FOREIGN KEY (`Tili_idTili`)
    REFERENCES `ER`.`Tili` (`idTili`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ER`.`Tilitapahtumat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ER`.`Tilitapahtumat` (
  `Tilinumero` INT NOT NULL,
  `Summa` INT NOT NULL,
  `Pvm` DATETIME NOT NULL,
  `Tili_idTili` INT NOT NULL,
  PRIMARY KEY (`Tilinumero`, `Tili_idTili`),
  INDEX `fk_Tilitapahtumat_Tili1_idx` (`Tili_idTili` ASC) VISIBLE,
  CONSTRAINT `fk_Tilitapahtumat_Tili1`
    FOREIGN KEY (`Tili_idTili`)
    REFERENCES `ER`.`Tili` (`idTili`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ER`.`Asiakas_has_Tili`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ER`.`Asiakas_has_Tili` (
  `Asiakas_idAsiakas` INT NOT NULL,
  `Tili_idTili` INT NOT NULL,
  PRIMARY KEY (`Asiakas_idAsiakas`, `Tili_idTili`),
  INDEX `fk_Asiakas_has_Tili_Tili1_idx` (`Tili_idTili` ASC) VISIBLE,
  INDEX `fk_Asiakas_has_Tili_Asiakas1_idx` (`Asiakas_idAsiakas` ASC) VISIBLE,
  CONSTRAINT `fk_Asiakas_has_Tili_Asiakas1`
    FOREIGN KEY (`Asiakas_idAsiakas`)
    REFERENCES `ER`.`Asiakas` (`idAsiakas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asiakas_has_Tili_Tili1`
    FOREIGN KEY (`Tili_idTili`)
    REFERENCES `ER`.`Tili` (`idTili`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
